### ISSUE TITLE
Nothing ripped; Throws disc out some seconds after inserting.

### ISSUE THREAD

**Issue by gsantner** [ahnooie/automatic-ripping-machine#46]
With the original config checked into the repo. Same folders and so on.

````
*** Start config parameters ****
ARM_CHECK_UDF=true
GET_VIDEO_TITLE=true
SKIP_TRANSCODE=false
RAWPATH="/mnt/media/ARM/raw/"
MEDIA_DIR="/mnt/media/ARM/Media/Movies/"
LOGPATH="/opt/arm/logs/"
LOGLIFE=1
SET_MEDIA_PERMISSIONS=false
CHMOD_VALUE=777
MINLENGTH="600"
RIPMETHOD="mkv" 
MKV_ARGS=""
HB_PRESET="High Profile" 
DEST_EXT=mkv
HANDBRAKE_CLI=HandBrakeCLI
MAINFEATURE=false
HB_ARGS="--subtitle scan -F"
PLEX_SUPPORT=false
EMBY_REFRESH=false
EMBY_SUBFOLDERS=true
EMBY_SERVER=""
EMBY_PORT="8096"
EMBY_CLIENT="ARM"
EMBY_DEVICE="ARM"
EMBY_DEVICEID="ARM"
EMBY_USERNAME=""
EMBY_USERID=""
IFTTT_EVENT="arm_event"
LOG=$LOGPATH$LOGFILE
*** End config parameters ****
Starting Identify Script...
Deleting 0 old log files: 
DEVLINKS=/dev/cdrom /dev/cdrw /dev/disk/by-id/ata-Slimtype_DVD_A_DS8A5SH_103280075052 /dev/disk/by-label/PAUL_BLART_MALL_COP /dev/disk/by-uuid/2009-06-13-07-20-10-77 /dev/dvd /dev/dvdrw
DEVNAME=/dev/sr0
DEVPATH=/devices/pci0000:00/0000:00:11.0/ata2/host1/target1:0:0/1:0:0:0/block/sr0
DEVTYPE=disk
ID_ATA=1
ID_ATA_SATA=1
ID_ATA_SATA_SIGNAL_RATE_GEN1=1
ID_BUS=ata
ID_CDROM=1
ID_CDROM_CD=1
ID_CDROM_CD_R=1
ID_CDROM_CD_RW=1
ID_CDROM_DVD=1
ID_CDROM_DVD_PLUS_R=1
ID_CDROM_DVD_PLUS_RW=1
ID_CDROM_DVD_PLUS_R_DL=1
ID_CDROM_DVD_R=1
ID_CDROM_DVD_RAM=1
ID_CDROM_DVD_RW=1
ID_CDROM_MEDIA=1
ID_CDROM_MEDIA_DVD=1
ID_CDROM_MEDIA_SESSION_COUNT=1
ID_CDROM_MEDIA_STATE=complete
ID_CDROM_MEDIA_TRACK_COUNT=1
ID_CDROM_MEDIA_TRACK_COUNT_DATA=1
ID_CDROM_MRW=1
ID_CDROM_MRW_W=1
ID_FS_LABEL=PAUL_BLART_MALL_COP
ID_FS_LABEL_ENC=PAUL_BLART_MALL_COP
ID_FS_TYPE=udf
ID_FS_USAGE=filesystem
ID_FS_UUID=2009-06-13-07-20-10-77
ID_FS_UUID_ENC=2009-06-13-07-20-10-77
ID_MODEL=Slimtype_DVD_A_DS8A5SH
ID_MODEL_ENC=Slimtype\x20DVD\x20A\x20\x20DS8A5SH\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
ID_REVISION=XA15
ID_SERIAL=Slimtype_DVD_A_DS8A5SH_103280075052
ID_SERIAL_SHORT=103280075052
ID_TYPE=cd
MAJOR=11
MINOR=0
SUBSYSTEM=block
TAGS=:seat:systemd:uaccess:
UDISKS_PRESENTATION_NOPOLICY=0
USEC_INITIALIZED=63842
identified udf
found PAUL_BLART_MALL_COP on /dev/sr0
identified udf as video
failed to get title Traceback (most recent call last):
  File "/opt/arm/getmovietitle.py", line 69, in <module>
    disc_title = clean_for_filename(getdvdtitle())
  File "/opt/arm/getmovietitle.py", line 31, in getdvdtitle
    dvd_title = doc['METADATA']['MDR-DVD']['dvdTitle']
KeyError: 'dvdTitle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/getmovietitle.py", line 71, in <module>
    disc_title = clean_for_filename(getbluraytitle())
  File "/opt/arm/getmovietitle.py", line 39, in getbluraytitle
    with open(args.path + '/BDMV/META/DL/bdmt_eng.xml', "rb") as xml_file:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/dev/sr0/BDMV/META/DL/bdmt_eng.xml'
got to here
HAS_NICE_TITLE is false
video title is now PAUL_BLART_MALL_COP
video type is unknown
Video Title is PAUL_BLART_MALL_COP
Ripping video PAUL_BLART_MALL_COP from /dev/sr0
Using mkv method of ripping.
STAT: PAUL_BLART_MALL_COP ripped in 0 hours, 0 minutes and 2 seconds.
/opt/arm/video_transcode.sh "/mnt/media/ARM/raw//PAUL_BLART_MALL_COP_20170204_181206" "PAUL_BLART_MALL_COP" "false" "unknown" 20170204_181206
PAUL_BLART_MALL_COP sent to transcoding queue...
Start video transcoding script
transcoding without a nice title
Transcoding all files.
STAT: PAUL_BLART_MALL_COP transcoded in 0 hours, 0 minutes and 0 seconds.
Pushbullet notifications not enabled
IFTTT notifications not enabled
*** Start config parameters ****
ARM_CHECK_UDF=true
GET_VIDEO_TITLE=true
SKIP_TRANSCODE=false
RAWPATH="/mnt/media/ARM/raw/"
MEDIA_DIR="/mnt/media/ARM/Media/Movies/"
LOGPATH="/opt/arm/logs/"
LOGLIFE=1
SET_MEDIA_PERMISSIONS=false
CHMOD_VALUE=777
MINLENGTH="600"
RIPMETHOD="mkv" 
MKV_ARGS=""
HB_PRESET="High Profile" 
DEST_EXT=mkv
HANDBRAKE_CLI=HandBrakeCLI
MAINFEATURE=false
HB_ARGS="--subtitle scan -F"
PLEX_SUPPORT=false
EMBY_REFRESH=false
EMBY_SUBFOLDERS=true
EMBY_SERVER=""
EMBY_PORT="8096"
EMBY_CLIENT="ARM"
EMBY_DEVICE="ARM"
EMBY_DEVICEID="ARM"
EMBY_USERNAME=""
EMBY_USERID=""
IFTTT_EVENT="arm_event"
LOG=$LOGPATH$LOGFILE
*** End config parameters ****
Starting Identify Script...
Deleting 0 old log files: 
DEVLINKS=/dev/cdrom /dev/cdrw /dev/disk/by-id/ata-Slimtype_DVD_A_DS8A5SH_103280075052 /dev/disk/by-label/PAUL_BLART_MALL_COP /dev/disk/by-uuid/2009-06-13-07-20-10-77 /dev/dvd /dev/dvdrw
DEVNAME=/dev/sr0
DEVPATH=/devices/pci0000:00/0000:00:11.0/ata2/host1/target1:0:0/1:0:0:0/block/sr0
DEVTYPE=disk
ID_ATA=1
ID_ATA_SATA=1
ID_ATA_SATA_SIGNAL_RATE_GEN1=1
ID_BUS=ata
ID_CDROM=1
ID_CDROM_CD=1
ID_CDROM_CD_R=1
ID_CDROM_CD_RW=1
ID_CDROM_DVD=1
ID_CDROM_DVD_PLUS_R=1
ID_CDROM_DVD_PLUS_RW=1
ID_CDROM_DVD_PLUS_R_DL=1
ID_CDROM_DVD_R=1
ID_CDROM_DVD_RAM=1
ID_CDROM_DVD_RW=1
ID_CDROM_MEDIA=1
ID_CDROM_MEDIA_DVD=1
ID_CDROM_MEDIA_SESSION_COUNT=1
ID_CDROM_MEDIA_STATE=complete
ID_CDROM_MEDIA_TRACK_COUNT=1
ID_CDROM_MEDIA_TRACK_COUNT_DATA=1
ID_FS_LABEL=PAUL_BLART_MALL_COP
ID_FS_LABEL_ENC=PAUL_BLART_MALL_COP
ID_FS_TYPE=udf
ID_FS_USAGE=filesystem
ID_FS_UUID=2009-06-13-07-20-10-77
ID_FS_UUID_ENC=2009-06-13-07-20-10-77
ID_MODEL=Slimtype_DVD_A_DS8A5SH
ID_MODEL_ENC=Slimtype\x20DVD\x20A\x20\x20DS8A5SH\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
ID_REVISION=XA15
ID_SERIAL=Slimtype_DVD_A_DS8A5SH_103280075052
ID_SERIAL_SHORT=103280075052
ID_TYPE=cd
MAJOR=11
MINOR=0
SUBSYSTEM=block
TAGS=:seat:systemd:uaccess:
UDISKS_PRESENTATION_NOPOLICY=0
USEC_INITIALIZED=63842
identified udf
found PAUL_BLART_MALL_COP on /dev/sr0
identified udf as video
failed to get title Traceback (most recent call last):
  File "/opt/arm/getmovietitle.py", line 69, in <module>
    disc_title = clean_for_filename(getdvdtitle())
  File "/opt/arm/getmovietitle.py", line 31, in getdvdtitle
    dvd_title = doc['METADATA']['MDR-DVD']['dvdTitle']
KeyError: 'dvdTitle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/getmovietitle.py", line 71, in <module>
    disc_title = clean_for_filename(getbluraytitle())
  File "/opt/arm/getmovietitle.py", line 39, in getbluraytitle
    with open(args.path + '/BDMV/META/DL/bdmt_eng.xml', "rb") as xml_file:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/dev/sr0/BDMV/META/DL/bdmt_eng.xml'
got to here
HAS_NICE_TITLE is false
video title is now PAUL_BLART_MALL_COP
video type is unknown
Video Title is PAUL_BLART_MALL_COP
Ripping video PAUL_BLART_MALL_COP from /dev/sr0
Using mkv method of ripping.
STAT: PAUL_BLART_MALL_COP ripped in 0 hours, 0 minutes and 2 seconds.
/opt/arm/video_transcode.sh "/mnt/media/ARM/raw//PAUL_BLART_MALL_COP_20170204_181228" "PAUL_BLART_MALL_COP" "false" "unknown" 20170204_181228
PAUL_BLART_MALL_COP sent to transcoding queue...
Start video transcoding script
transcoding without a nice title
Transcoding all files.
STAT: PAUL_BLART_MALL_COP transcoded in 0 hours, 0 minutes and 0 seconds.
Pushbullet notifications not enabled
IFTTT notifications not enabled
````

Failure mails from mbox:
```
From root@somewhere Sat Feb 04 18:12:31 2017
Envelope-to: root@somewhere
Delivery-date: Sat, 04 Feb 2017 18:12:31 +0100
Subject: Output from your job        7
To: root@somewhere
From: root <root@somewhere>
Date: Sat, 04 Feb 2017 18:12:31 +0100

/opt/arm/config
/opt/arm/identify.sh: line 109: ((: > 0 : syntax error: operand expected (error token is "> 0 ")

& 
Message 7:
From root@somewhere Sat Feb 04 18:13:08 2017
Envelope-to: root@somewhere
Delivery-date: Sat, 04 Feb 2017 18:13:08 +0100
Subject: Output from your job        6
To: root@somewhere
From: root <root@somewhere>
Date: Sat, 04 Feb 2017 18:13:08 +0100

rmdir: failed to remove '/mnt/media/ARM/raw//PAUL_BLART_MALL_COP_20170204_181228': No such file or directory
warning: commands will be executed using /bin/sh
job 8 at Sat Feb  4 18:13:00 2017
```

**Comment by RandomNinjaAtk** [comment]
Try setting "skip_transpose" to "true". This will bypass using handbrake and use makemkv to rip the disc. If that works then it's a problem with handbrake somewhere. I don't transpose, so I won't be of much helpower. But running a test this way will let you see if at least makemkv us functioning normally.
