### ISSUE TITLE
Pip3 install error UBuntu 16.10

### ISSUE THREAD

**Issue by creiners** [ahnooie/automatic-ripping-machine#49]
I'm a noob but I have followed precisely every step(wiped system clean and verified) but I get this error when I reach the step:  pip3 install -r requirements.txt

root@ubuntu:/opt/arm# pip3 install -r requirements.txt
Collecting pycurl>=7.43.0 (from -r requirements.txt (line 1))
  Using cached pycurl-7.43.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-build-mkcaaprp/pycurl/setup.py", line 103, in configure_unix
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'curl-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mkcaaprp/pycurl/setup.py", line 823, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-build-mkcaaprp/pycurl/setup.py", line 497, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-build-mkcaaprp/pycurl/setup.py", line 71, in __init__
        self.configure()
      File "/tmp/pip-build-mkcaaprp/pycurl/setup.py", line 107, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mkcaaprp/pycurl/
root@ubuntu:/opt/arm#

**Comment by RandomNinjaAtk** [comment]
There are known problems using this scrip with Ubuntu 16.10, my recommendation would be to use Ubuntu 16.04 instead...

**Comment by creiners** [comment]
Ok.  Had some issues getting 16.04 installed on this machine but I'll give it another go

**Comment by ahnooie** [comment]
@creiners 16.04 is definitely the way to go, let me know what issues you run into, if needed we'll update the install documentation.

**Comment by creiners** [comment]
The instructions worked flawless on 16.04.  Thank you for the quick responses.

**Comment by ahnooie** [comment]
Glad to hear.  Thanks for reporting back.
